# Ejemplo Ortogonalización de Gram-Schmitd usando Numpy

In [0]:
import numpy as np

In [0]:
A = np.array([[1,0,0],[1,1,0],[1,1,1],[1,1,1]])
print(A)

[[1 0 0]
 [1 1 0]
 [1 1 1]
 [1 1 1]]


In [0]:
q1 = A[:,0]
q1 = q1/np.linalg.norm(q1)
print(q1)

[0.5 0.5 0.5 0.5]


In [0]:
a2 = A[:,1]
q2 = a2 - np.dot(q1,a2)*q1
print(q2)

[-0.75  0.25  0.25  0.25]


In [0]:
q2 = q2/np.linalg.norm(q2)
print(q2)

[-0.8660254   0.28867513  0.28867513  0.28867513]


In [0]:
a3 = A[:,2]
q3 = a3 - np.dot(q1,a3)*q1 - np.dot(q2,a3)*q2
print(q3)

[ 1.11022302e-16 -6.66666667e-01  3.33333333e-01  3.33333333e-01]


In [0]:
print(np.dot(q1,q2))
print(np.dot(q1,q3))
print(np.dot(q2,q3))

5.551115123125783e-17
-5.551115123125783e-17
-1.3877787807814457e-16


In [0]:
B = np.random.rand(3,3)
B = B*B.T
print(B)

[[0.95239475 0.01397339 0.23838464]
 [0.01397339 0.991237   0.06748269]
 [0.23838464 0.06748269 0.76512189]]


In [0]:
L=np.linalg.cholesky(B)
print(L)

[[0.97590714 0.         0.        ]
 [0.01431836 0.99550589 0.        ]
 [0.2442698  0.064274   0.8374503 ]]


In [0]:
B2 = L@L.T
print(B2)


[[0.95239475 0.01397339 0.23838464]
 [0.01397339 0.991237   0.06748269]
 [0.23838464 0.06748269 0.76512189]]


In [0]:
print(np.sum(B-B2))

5.551115123125783e-17


In [0]:
lam, V=np.linalg.eig(B)

In [0]:
print(lam)

[0.59675794 1.13276995 0.97922575]


In [0]:
print(V)

[[ 0.54932298 -0.75954449  0.3483338 ]
 [ 0.12195705 -0.33952255 -0.93265798]
 [-0.82666241 -0.55481222  0.09387573]]


In [0]:
B@V

array([[ 0.32781285, -0.86038918,  0.34109742],
       [ 0.07277884, -0.38460095, -0.91328271],
       [-0.49331736, -0.62847461,  0.09192553]])

In [0]:
V*lam

array([[ 0.32781285, -0.86038918,  0.34109742],
       [ 0.07277884, -0.38460095, -0.91328271],
       [-0.49331736, -0.62847461,  0.09192553]])

In [0]:
np.linalg.matrix_rank(B)

3