In [0]:
import autograd.numpy as np
import autograd as ag

## Jacobiano de una funcion escalar

In [25]:
def f(x, y):
    return x**(.8) * y**(.2)

dfdx = grad(f)
dfdy = grad(f, 1)

x, y = 2.0, 3.0

derivs = np.array([dfdx(x,y), dfdy(x,y)])
print("Gradente: ", derivs)

Gradente:  [0.86757742 0.14459624]


# Gradiente del producto matriz vector

In [0]:
def mv(x):
    A = np.arange(9, dtype=np.float).reshape(3,3)
    return np.dot(A, x)

In [24]:
jac = ag.jacobian(mv)
x = np.arange(3, dtype=np.float)
print(f(x))
print(jac(x))

[ 5. 14. 23.]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
