# Factorizacion de matrices

Basado en los comandos descritos en [Numpy.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html)

## 1. Descomposición LU



Para esta descomposicion usaremos la libreria Scipy.

In [27]:
from scipy.linalg import lu
import numpy as np

El comando lu de Scipy nos retorna $\mathbf{PA}=\mathbf{LU}$, $\mathbf{A}=\mathbf{PLU}$

In [28]:
A = np.array([[2,4,-1,5,-2],[-4,-5,3,-8,1],[2,-5,-4,1,8],[-6,0,7,-3,1]])
P, L, U = lu(A)
print(P)
print(L)
print(U)
print(P@(L@U))

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333  1.          1.          0.        ]
 [-0.33333333 -0.8        -0.          1.        ]]
[[-6.00000000e+00  0.00000000e+00  7.00000000e+00 -3.00000000e+00
   1.00000000e+00]
 [ 0.00000000e+00 -5.00000000e+00 -1.66666667e+00 -6.00000000e+00
   3.33333333e-01]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16  6.00000000e+00
   8.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -8.00000000e-01
  -1.40000000e+00]]
[[ 2.  4. -1.  5. -2.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [-6.  0.  7. -3.  1.]]


In [29]:
print(P@A)
print(L@U)

[[-6.  0.  7. -3.  1.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [ 2.  4. -1.  5. -2.]]
[[-6.  0.  7. -3.  1.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [ 2.  4. -1.  5. -2.]]


Solucion de sistemas de ecuacion con LU, $\mathbf{A}\mathbf{x}=\mathbf{b}$, con <br>
$$ \mathbf{A} = \begin{bmatrix} 3 & -7 & -2\\ -3 & 5 & 1\\ 6 & -4 & 0 \end{bmatrix} \quad \mathbf{b} = \begin{bmatrix} -7\\ 5\\ 2 \end{bmatrix}$$

In [80]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
b = np.array([[-7],[5],[2]])

In [31]:
x2 = np.linalg.solve(A,b)
x2

array([[ 3.],
       [ 4.],
       [-6.]])

Recordar que $\mathbf{PA}=\mathbf{LU}$, entonces $\mathbf{LU}\mathbf{x}=\mathbf{Pb}$, $\mathbf{PAx}=\mathbf{Pb}$

In [82]:
P,L,U = lu(A)

In [33]:
print(P,'\n',L,'\n',U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5 -0.6  1. ]] 
 [[ 6.  -4.   0. ]
 [ 0.  -5.  -2. ]
 [ 0.   0.  -0.2]]


La solucion es $\mathbf{x}=\mathbf{U}^{-1}\mathbf{L}^{-1}\mathbf{P}\mathbf{b}$

In [85]:
z = np.linalg.solve(L,P.T@b)
x = np.linalg.solve(U,z)
print(x)

[[ 3.]
 [ 4.]
 [-6.]]


In [35]:
print(P@(A@x))
print(b)

[[-7.]
 [ 5.]
 [ 2.]]
[[-7]
 [ 5]
 [ 2]]


## 2. Descomposicion QR

Aqui hacemos uso de la funcion qr dentron de la sub-libreria linalg de Numpy.

In [51]:
A = np.array([[1,0,0],[1,1,0],[1,1,1],[1,1,1]])
print(A)

[[1 0 0]
 [1 1 0]
 [1 1 1]
 [1 1 1]]


In [53]:
Q,R = np.linalg.qr(A)
print(Q,'\n \n',R)

[[-0.5         0.8660254   0.        ]
 [-0.5        -0.28867513  0.81649658]
 [-0.5        -0.28867513 -0.40824829]
 [-0.5        -0.28867513 -0.40824829]] 
 
 [[-2.         -1.5        -1.        ]
 [ 0.         -0.8660254  -0.57735027]
 [ 0.          0.         -0.81649658]]


In [55]:
Q@R

array([[ 1.00000000e+00,  8.69063787e-17, -1.34358683e-16],
       [ 1.00000000e+00,  1.00000000e+00,  1.61842956e-16],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00]])

In [54]:
Q.T@Q

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 6.34802232e-18],
       [0.00000000e+00, 6.34802232e-18, 1.00000000e+00]])

In [56]:
A = np.array([[4,0],[0,2],[1,1]])
print(A)

[[4 0]
 [0 2]
 [1 1]]


In [58]:
Q,R = np.linalg.qr(A)
print(Q,'\n \n', R)

[[-0.9701425   0.10585122]
 [-0.         -0.89973541]
 [-0.24253563 -0.4234049 ]] 
 
 [[-4.12310563 -0.24253563]
 [ 0.         -2.22287572]]


In [59]:
b = np.array([[2],[0],[11]])

In [60]:
xc1 = np.linalg.solve(R,(Q.T@b))
xc1

array([[1.],
       [2.]])

In [62]:
xc2 = np.linalg.solve(A.T@A,(A.T@b))
xc2

array([[1.],
       [2.]])

In [63]:
xc3 = np.linalg.pinv(A)@b
xc3

array([[1.],
       [2.]])

In [69]:
np.linalg.norm(b-A@(xc1))

9.16515138991168

## 3. Descomposición en valores singulares

Para este caso usamos el comando svd en la sub-libreria linalg de Numpy.

In [74]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
b = np.array([[-7],[5],[2]])
U,S,V = np.linalg.svd(A)
print(U)
print(S)
print(V)

[[-0.65027495  0.57696259 -0.49422329]
 [ 0.50165302 -0.1624368  -0.84968143]
 [-0.57051445 -0.80045515 -0.18380645]]
[11.74071486  3.33648831  0.15316767]
[[-0.58589879  0.79571369  0.15350027]
 [-0.77462664 -0.49426265 -0.39453517]
 [-0.23806759 -0.35006308  0.90596891]]


In [77]:
V.T@V

array([[ 1.00000000e+00, -6.80091366e-17,  2.98605952e-17],
       [-6.80091366e-17,  1.00000000e+00,  1.57357181e-16],
       [ 2.98605952e-17,  1.57357181e-16,  1.00000000e+00]])

In [71]:
np.sqrt(S)

array([3.42647266, 1.82660568, 0.39136641])

In [75]:
np.linalg.eigvals(A)

array([6.62778979+0.j        , 0.68610511+0.65919568j,
       0.68610511-0.65919568j])

In [40]:
S.shape

(3,)

In [78]:
print(U.T@U)
print(V.T@V)
print(np.prod(S))
print(np.linalg.det(A))

[[ 1.00000000e+00  1.51480715e-16 -3.66980942e-17]
 [ 1.51480715e-16  1.00000000e+00 -2.18043275e-16]
 [-3.66980942e-17 -2.18043275e-16  1.00000000e+00]]
[[ 1.00000000e+00 -6.80091366e-17  2.98605952e-17]
 [-6.80091366e-17  1.00000000e+00  1.57357181e-16]
 [ 2.98605952e-17  1.57357181e-16  1.00000000e+00]]
5.9999999999999964
6.0000000000000036


In [42]:
np.diag(S)

array([[9.88531219, 0.        , 0.        ],
       [0.        , 7.0434192 , 0.        ],
       [0.        , 0.        , 1.29261319]])

In [43]:
print(U@np.diag(S)@V)
print(A)

[[ 3.00000000e+00  7.00000000e+00 -2.00000000e+00]
 [-3.00000000e+00  5.00000000e+00  1.00000000e+00]
 [ 6.00000000e+00 -4.00000000e+00  1.61671397e-16]]
[[ 3  7 -2]
 [-3  5  1]
 [ 6 -4  0]]


Si $\mathbf{A}\mathbf{x}=\mathbf{b}$ entonces $\mathbf{USV}^{\top}\mathbf{x}=\mathbf{b}$, entonces $\mathbf{x}=\mathbf{VS}^{-1}\mathbf{U}^{\top}\mathbf{b}$

In [44]:
x = V.T@np.diag(1/S)@U.T@b
print(x)

[[0.51111111]
 [0.26666667]
 [5.2       ]]


In [45]:
print(A@x)
print(b)

[[-7.]
 [ 5.]
 [ 2.]]
[[-7]
 [ 5]
 [ 2]]


## 4. Pseudo inversas

Para matrices rectangulares $\mathbf{A}$, la pseudo inversa es $\mathbf{A}^{\dagger}=(\mathbf{A^{\top}}\mathbf{A})^{-1}\mathbf{A}^{\top}$.

In [46]:
A1 = np.array([[2,4,-1,5,-2],[-4,-5,3,-8,1],[2,-5,-4,1,8],[-6,0,7,-3,1]])
A2 = np.array([[1,0,0],[1,1,0],[1,1,1],[1,1,1]])
print(A1.shape,A2.shape)

(4, 5) (4, 3)


In [47]:
A1pinv = np.linalg.pinv(A1)
A2pinv = np.linalg.pinv(A2)

In [48]:
print(A1@A1pinv)

[[ 1.00000000e+00  0.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 4.88498131e-15  1.00000000e+00  1.66533454e-16 -1.66533454e-16]
 [ 1.06581410e-14  7.10542736e-15  1.00000000e+00 -2.22044605e-16]
 [-7.54951657e-15 -5.77315973e-15 -1.49880108e-15  1.00000000e+00]]


In [49]:
print(A2pinv@A2)

[[ 1.00000000e+00 -9.36770127e-16 -3.72473284e-16]
 [ 9.30344823e-17  1.00000000e+00  5.37123692e-16]
 [ 3.33066907e-16 -2.77555756e-16  1.00000000e+00]]
