# Solucion de sistema de ecuaciones usando la factorización LU

In [0]:
import numpy as np
from scipy.linalg import lu

En este caso queremos encontrar la solucion al problema $\mathbf{A}\mathbf{x}=\mathbf{b}$, con<br>
$\mathbf{A}=\begin{bmatrix} 3 & -7 & -2\\ -3 & 5 & 1\\ 6 & -4 & 0 \end{bmatrix}$, $\mathbf{b}=\begin{bmatrix} -7 \\ 5\\ 2\end{bmatrix}$.

In [0]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
b = np.array([-7,5,2])

Podemos calcular la solucion empleando la funcion lu de la libreria scipy.

In [3]:
P,L,U = lu(A) #P es una matriz de permitacion ortogonal
print(P,'\n',L,'\n',U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5 -0.6  1. ]] 
 [[ 6.  -4.   0. ]
 [ 0.  -5.  -2. ]
 [ 0.   0.  -0.2]]


El sistema de ecuaciones se resuelve, primero calculando $\mathbf{L}\mathbf{y}=\mathbf{b}$ y luego $\mathbf{R}\mathbf{x}=\mathbf{y}$. Empezamos calculando $\mathbf{y}$ a partir de la solcuión de $\mathbf{L}\mathbf{y}=\mathbf{b}$.

In [4]:
y=np.linalg.solve(L,np.dot(P.T,b)) #Se realiza el producto P^T*b para cambiar el orden de b de acuerdo a P
print(y)

[ 2.  -8.   1.2]


Calculamos la solucion de $\mathbf{x}$, utiliazndo $\mathbf{R}\mathbf{x}=\mathbf{y}$.

In [5]:
x=np.linalg.solve(U,y)
print(x)

[ 3.  4. -6.]


La comparamos con la solución que se encuentra usando $\mathbf{A}\mathbf{x}=\mathbf{b}$.

In [6]:
x2 = np.linalg.solve(A,b)
print(x2)

[ 3.  4. -6.]
